import { createVuetify } from "vuetify";
import {
  VToolbarTitle,
  VAppBar,
  VListItemTitle,
  VDivider,
  VList,
  VNavigationDrawer,
  VContainer,
  VMain,
  VFooter,
  VApp,
  VListItem,
  VCardTitle,
  VTab,
  VTabs,
  VTextField,
  VBtn,
  VForm,
  VCardText,
  VCard,
  VCol,
  VRow,
  VSelect,
  VAlert,
  VSpacer,
  VSlideGroup,
  VCardSubtitle,
  VCardActions,
  VSlideGroupItem,
  VSnackbar,
  VMenu,
  VDatePicker,
  VTextarea,
  VDialog,
  VCheckbox,
  VLabel,
} from "vuetify/components";
import { VTimePicker } from "vuetify/lib/labs/components.mjs";
import { aliases, mdi } from "vuetify/iconsets/mdi";
import "vuetify/styles";
import "@mdi/font/css/materialdesignicons.css";
import DayJsAdapter from "@date-io/dayjs";

export default createVuetify({
  components: {
    VToolbarTitle,
    VAppBar,
    VListItemTitle,
    VDivider,
    VList,
    VNavigationDrawer,
    VContainer,
    VMain,
    VFooter,
    VApp,
    VListItem,
    VCardTitle,
    VTab,
    VTabs,
    VTextField,
    VBtn,
    VForm,
    VCardText,
    VCard,
    VCol,
    VRow,
    VSelect,
    VAlert,
    VSpacer,
    VSlideGroup,
    VCardSubtitle,
    VCardActions,
    VSlideGroupItem,
    VTimePicker,
    VSnackbar,
    VMenu,
    VDatePicker,
    VTextarea,
    VDialog,
    VCheckbox,
    VLabel,
  },
  icons: {
    defaultSet: "mdi",
    aliases,
    sets: {
      mdi,
    },
  },
  theme: {
    themes: {
      light: {
        colors: {
          primary: "#212fad",
          secondary: "#68a1cc",
        },
      },
    },
  },
  date: {
    adapter: DayJsAdapter,
  },
});
